add_newline = false

format = """
$time\
$direnv\
$directory\
$git_branch\
$git_status\
$python\
$aws\
$conda\
$kubernetes\
$line_break\
$character
"""
[direnv]
disabled = false

[time]
disabled = false
format = "[$time]($style) "

[battery]
disabled = true

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vicmd_symbol = "[<](bold green)"

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[conda]
ignore_base = false
disabled = false
format = "[$symbol$environment]($style) "

[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[directory]
read_only = " ro"

[docker_context]
symbol = "docker "

[gcloud]
symbol = "gcp:"
format = "[$symbol$account(@$domain)(($region))]($style) "
style = "bold green"

[git_branch]
format = "[$symbol$branch]($style) "

[golang]
symbol = "go "

[kubernetes]
disabled = false
format = "[$symbol$context\\($namespace\\)]($style)"

[memory_usage]
symbol = "memory "

[nix_shell]
symbol = "nix "

[package]
symbol = "pkg "

[python]
format = "[${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"
symbol = "py:"

[rust]
symbol = "rs "

[scala]
symbol = "scala "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "