#!/bin/bash

# Copyright (C) 2014 Jonathan Jin <jonathan@jjin.me>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

TAGS="+school"
CMD="task $TAGS next"
TASKSETTINGS="rc.report.next.labels:Desc rc.report.next.columns:description"
FONT="Terminus:8"

HEADERHEIGHT=4
FOOTERHEIGHT=1

$CMD $TASKSETTINGS 2>/dev/null | tail -n +$HEADERHEIGHT | head -n $FOOTERHEIGHT

if [ -n "$BLOCK_BUTTON" ]; then
  tasks=$($CMD | head -n -2)

  NUMLINES=$(echo "$tasks" | wc -l)

  echo "$tasks" | dzen2 \
    -x $BLOCK_X \
    -y 2 \
    -w 700 \
    -l $NUMLINES \
    -p 3 \
    -e "onstart=uncollapse,hide" \
    -fn $FONT \
    -fg "#d6a344"
fi
